<?php

namespace T2V\AdminBundle\Repository;

/**
 * DetailLivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailLivreRepository extends \Doctrine\ORM\EntityRepository
{
}
