souscategorie_index:
    path:     /
    defaults: { _controller: "T2VAdminBundle:SousCategorie:index" }
    methods:  GET

souscategorie_show:
    path:     /{id}/show
    defaults: { _controller: "T2VAdminBundle:SousCategorie:show" }
    methods:  GET

souscategorie_new:
    path:     /new
    defaults: { _controller: "T2VAdminBundle:SousCategorie:new" }
    methods:  [GET, POST]

souscategorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "T2VAdminBundle:SousCategorie:edit" }
    methods:  [GET, POST]

souscategorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "T2VAdminBundle:SousCategorie:delete" }
    methods:  DELETE
